#Numpy For data analysis

In [ ]:
import numpy as np

x = [10,25,15,13,16,17]

print(x*2)

[10, 25, 15, 13, 16, 17, 10, 25, 15, 13, 16, 17]


In [ ]:
# without using numy
for i in x:
  print(i*2)

20
50
30
26
32
34


In [ ]:
#using numpy
y = np.array(x)
print(type(y))
print(y*2)
print(y>13)
print(y[y>13])

<class 'numpy.ndarray'>
[20 50 30 26 32 34]
[False  True  True False  True  True]
[25 15 16 17]


In [ ]:
y

array([10, 25, 15, 13, 16, 17])

In [ ]:
z =y -10


In [ ]:
z

array([ 0, 15,  5,  3,  6,  7])

#random

In [ ]:
from numpy import random

x = random.randint(2,20)
print(x)

3


In [ ]:
import numpy as np
data = [10,20,30,40,50,60,70]
print(data*2)

#using numpy

result = np.array(data)
print(result*2)

[10, 20, 30, 40, 50, 60, 70, 10, 20, 30, 40, 50, 60, 70]
[ 20  40  60  80 100 120 140]


In [ ]:
import numpy as np
a = np.arange(10)
print(a)
b = a[::2]
print(b)
print(np.shares_memory(a,b)) #checks whether a and b shares memory
print(a,"\n",b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
True
[0 1 2 3 4 5 6 7 8 9] 
 [0 2 4 6 8]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5,6],[5,6,7,8,9,10]])
print(type(arr))
print()
print(arr)
print(arr[0,-1])
print(arr[1,-3])

print(arr[0])
print(arr[1])

<class 'numpy.ndarray'>

[[ 1  2  3  4  5  6]
 [ 5  6  7  8  9 10]]
6
8
[1 2 3 4 5 6]
[ 5  6  7  8  9 10]


#slicing

In [ ]:
import numpy as np
arr = np.array([1,2,5,98,7,5,12])
print(arr[2:5])

[ 5 98  7]


In [ ]:
print(arr[1:6:2])

[ 2 98  5]


#masking arrrays

In [ ]:
a = np.arange(15)
print(a)

mask = (a%2==0) #masking even numbers
print(a[mask])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]


In [ ]:
a = np.arange(15)
print(a)

mask = (a%2!=0) #masking even numbers
print(a[mask])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  3  5  7  9 11 13]


In [ ]:
a%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

#numpy matrices

In [ ]:
a = np.matrix('1,2;3,4')
print(a)
b = np.matrix([[1,2],[4,5]])
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [4 5]]


#numpy broad casting

In [ ]:
a = np.arange(0,40,5)

print(a)

b = np.arange(0,30,6)
print(b)

print(a.shape) #checking how many elements are there
print(a)

print()
print(b.shape)
print(b)

[ 0  5 10 15 20 25 30 35]
[ 0  6 12 18 24]
(8,)
[ 0  5 10 15 20 25 30 35]

(5,)
[ 0  6 12 18 24]


In [ ]:
a =a[:,np.newaxis]
a.shape

(8, 1, 1)

In [ ]:
print(a)

[[[ 0]]

 [[ 5]]

 [[10]]

 [[15]]

 [[20]]

 [[25]]

 [[30]]

 [[35]]]


In [ ]:
b

array([ 0,  6, 12, 18, 24])

In [ ]:
a+b

array([[[ 0,  6, 12, 18, 24]],

       [[ 5, 11, 17, 23, 29]],

       [[10, 16, 22, 28, 34]],

       [[15, 21, 27, 33, 39]],

       [[20, 26, 32, 38, 44]],

       [[25, 31, 37, 43, 49]],

       [[30, 36, 42, 48, 54]],

       [[35, 41, 47, 53, 59]]])

#DATA STRUCTURE

##Array/Vectors

In [3]:
from array import *

array1 = array ("i",[10,20,30,40,50])
print(array1)
for x in array1:
  print(x*2)

array('i', [10, 20, 30, 40, 50])
20
40
60
80
100


In [4]:
help(array)

Help on class array in module array:

class array(builtins.object)
 |  array(typecode [, initializer]) -> array
 |  
 |  Return a new array whose items are restricted by typecode, and
 |  initialized from the optional initializer value, which must be a list,
 |  string or iterable over elements of the appropriate type.
 |  
 |  Arrays represent basic values and behave very much like lists, except
 |  the type of objects stored in them is constrained. The type is specified
 |  at object creation time by using a type code, which is a single character.
 |  The following type codes are defined:
 |  
 |      Type code   C Type             Minimum size in bytes
 |      'b'         signed integer     1
 |      'B'         unsigned integer   1
 |      'u'         Unicode character  2 (see note)
 |      'h'         signed integer     2
 |      'H'         unsigned integer   2
 |      'i'         signed integer     2
 |      'I'         unsigned integer   2
 |      'l'         signed integer    

#array insertion and deletion operations

In [8]:
from array import *

a = array('i',[1,2,3,5,4])

print(a)

array('i', [1, 2, 3, 5, 4])


In [10]:
a.append(10)

In [11]:
a

array('i', [1, 2, 3, 5, 4, 10])

In [12]:
a.insert(15,5)

In [13]:
a

array('i', [1, 2, 3, 5, 4, 10, 5])

In [14]:
a.insert(1,100)

In [15]:
a

array('i', [1, 100, 2, 3, 5, 4, 10, 5])

In [18]:
for i in a:
  print(i)

1
100
2
3
5
4
10


In [17]:
a.pop()

5

In [19]:
a.remove(100) # it will remove the first occurance

In [20]:
a

array('i', [1, 2, 3, 5, 4, 10])

In [28]:
a.reverse()

In [29]:
a

array('i', [10, 4, 5, 3, 2, 1])

In [30]:
#update
a[2] = 25

In [31]:
a

array('i', [10, 4, 25, 3, 2, 1])

In [32]:
for i in a:
  print(i)

10
4
25
3
2
1


#2D array

In [34]:
x

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [3, 6, 9, 12, 15, 18]]

In [35]:
print(x[0])

[1, 2, 3, 4, 5, 6]


In [39]:
for i in x[2]:
  print(i)

3
6
9
12
15
18


In [56]:
print(x[0])

[1, 2, 3, 4, 5, 6]


In [57]:
print(x[1][2])

6


##inserting data into 2d array

In [69]:
from array import *

In [66]:
array1 = [ [1,2,3,4,5,6],[2,4,6,8,10,12],[3,6,9,12,15,18] ]
print(array1)

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [3, 6, 9, 12, 15, 18]]


In [67]:
array2 = [100,150,200,250,300]

In [70]:
array2.insert(2,255)

In [71]:
array2

[100, 150, 255, 200, 250, 300]

In [72]:
array1.append(array2)

In [73]:
array1

[[1, 2, 3, 4, 5, 6],
 [2, 4, 6, 8, 10, 12],
 [3, 6, 9, 12, 15, 18],
 [100, 150, 255, 200, 250, 300]]

In [75]:
array1.pop()

[100, 150, 255, 200, 250, 300]

In [76]:
array1.insert(2,array2)

In [77]:
array1

[[1, 2, 3, 4, 5, 6],
 [2, 4, 6, 8, 10, 12],
 [100, 150, 255, 200, 250, 300],
 [3, 6, 9, 12, 15, 18]]

In [78]:
array1[2][0]=101

In [82]:
array1

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [0, 200, 25], [3, 6, 9, 12, 15, 18]]

In [81]:
array1[2]=[0,200,25]

In [83]:
array1

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [0, 200, 25], [3, 6, 9, 12, 15, 18]]

In [84]:
del array1[2]

In [85]:
array1

[[1, 2, 3, 4, 5, 6], [2, 4, 6, 8, 10, 12], [3, 6, 9, 12, 15, 18]]

#matrix

In [98]:
from numpy import *
a = array([['Monday', 18, 20, 22, 17 ],['Tuesday', 11, 25, 15, 16],
['Wednesday', 18, 14, 17, 21],['Thursday', 1, 5, 7, 27],['Friday', 1, 5, 8, 7],
['Saturday',14,16,18,20],['Sunday',3,6,9,12]])
print(a)

[['Monday' '18' '20' '22' '17']
 ['Tuesday' '11' '25' '15' '16']
 ['Wednesday' '18' '14' '17' '21']
 ['Thursday' '1' '5' '7' '27']
 ['Friday' '1' '5' '8' '7']
 ['Saturday' '14' '16' '18' '20']
 ['Sunday' '3' '6' '9' '12']]


In [104]:
x = reshape(a,(7,5))
x

array([['Monday', '18', '20', '22', '17'],
       ['Tuesday', '11', '25', '15', '16'],
       ['Wednesday', '18', '14', '17', '21'],
       ['Thursday', '1', '5', '7', '27'],
       ['Friday', '1', '5', '8', '7'],
       ['Saturday', '14', '16', '18', '20'],
       ['Sunday', '3', '6', '9', '12']], dtype='<U21')

In [107]:
x[2][1:]

array(['18', '14', '17', '21'], dtype='<U21')

##adding row and column

In [136]:
from numpy import *
a = array([['Monday', 18, 20, 22, 17 ],['Tuesday', 11, 25, 15, 16],
['Wednesday', 18, 14, 17, 21],['Thursday', 1, 5, 7, 27],['Friday', 1, 5, 8, 7],
['Saturday',14,16,18,20],['Sunday',3,6,9,12]])

x = reshape(a,(7,5))


row = append(x,[['hello',15,152,16,12]],0) # adding row
print(row)

column =insert(x,[3],[[0],[1],[2],[4],[5],[7],[11]],1)

print(column)

[['Monday' '18' '20' '22' '17']
 ['Tuesday' '11' '25' '15' '16']
 ['Wednesday' '18' '14' '17' '21']
 ['Thursday' '1' '5' '7' '27']
 ['Friday' '1' '5' '8' '7']
 ['Saturday' '14' '16' '18' '20']
 ['Sunday' '3' '6' '9' '12']
 ['hello' '15' '152' '16' '12']]
[['Monday' '18' '20' '0' '22' '17']
 ['Tuesday' '11' '25' '1' '15' '16']
 ['Wednesday' '18' '14' '2' '17' '21']
 ['Thursday' '1' '5' '4' '7' '27']
 ['Friday' '1' '5' '5' '8' '7']
 ['Saturday' '14' '16' '7' '18' '20']
 ['Sunday' '3' '6' '11' '9' '12']]


##delete matric

In [151]:
n1 = delete (x[1], 0) # 0 is row

In [162]:
n2 = delete(x [2] , 2)# 2nd column means column

In [160]:
print(n1)

['11' '25' '15' '16']


In [161]:
print(n2)

['Wednesday' '18' '17' '21']


In [158]:
print(x)

[['Monday' '18' '20' '22' '17']
 ['Tuesday' '11' '25' '15' '16']
 ['Wednesday' '18' '14' '17' '21']
 ['Thursday' '1' '5' '7' '27']
 ['Friday' '1' '5' '8' '7']
 ['Saturday' '14' '16' '18' '20']
 ['Sunday' '3' '6' '9' '12']]


#diagonal

In [168]:
import numpy as np

z = np.diag(1+np.arange(5))
print(np.arange(5))
print(z)
print(type(z))

[0 1 2 3 4]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
<class 'numpy.ndarray'>
