In [ ]:
import numpy as np

In [ ]:
arr = np.array([20,15,16,18,15])

In [ ]:
print(type(arr)) #single dimensions

<class 'numpy.ndarray'>


In [ ]:
arr

array([20, 15, 16, 18, 15])

In [ ]:
arr2 =np.array(((25,11,16,15,8),(25,45,87,45,45)))



In [ ]:
arr2

array([[25, 11, 16, 15,  8],
       [25, 45, 87, 45, 45]])

In [ ]:
arr2.ndim #2dimensions

2

In [ ]:
arr.ndim

1

In [ ]:
arr3 = np.array([[10,20,30],[20,30,60],[10,20,15]])
print(arr3.ndim)

2


In [ ]:
arr4 = arr3 *2

In [ ]:
arr4

array([[ 20,  40,  60],
       [ 40,  60, 120],
       [ 20,  40,  30]])

In [ ]:
arr5 =[[10,20,30],[20,30,60],[10,20,15]]

In [ ]:
import time
sqr_empty_list= []
for i in arr5:
  t = [] #checking how this working
  # print(t)
  for j in i:
    t.append(j*2)
    print(t)
    time.sleep(10)
  sqr_empty_list.append(t)
sqr_empty_list


[20]
[20, 40]
[20, 40, 60]
[40]
[40, 60]
[40, 60, 120]
[20]
[20, 40]
[20, 40, 30]


[[20, 40, 60], [40, 60, 120], [20, 40, 30]]

In [ ]:



arr5 = [[10, 20, 30], [20, 30, 60], [10, 20, 15]]

sqr_nested_list = []
for i in arr5:
    temp = []  # Create a temporary list to store the multiplied values for the current sublist
    for j in i:
        temp.append(j * 2)  # Multiply each element by 2 and append to temp
    sqr_nested_list.append(temp)  # Append the multiplied sublist to the result list

sqr_nested_list


[[20, 40, 60], [40, 60, 120], [20, 40, 30]]

In [ ]:
arr5 = [[10, 20, 30], [20, 30, 60], [10, 20, 15]]
arr6 =[[10, 20, 30], [20, 30, 60], [10, 20, 15]]

arr5.extend(arr6)

In [ ]:
a =np.array(sqr_nested_list)
a.ndim

2

# about dimension in simple words
* 10  is 0
* [10] is 1d
* [[10],[20]] is 2d
* [[[10],[20]],[0],[25]]] is 3d

In [ ]:
arr7 = np.array([[[10, 20, 30], [20, 30, 60]],[[10,20,50],[1,5,8]]])


In [ ]:
arr7.ndim

3

In [ ]:
arr7*4

array([[[ 40,  80, 120],
        [ 80, 120, 240]],

       [[ 40,  80, 200],
        [  4,  20,  32]]])

#5d array

In [ ]:
five_d = np.array([1,2,3,4,5],ndmin =5)

In [ ]:
five_d #array([[[[[1, 2, 3, 4, 5]]]]])

array([[[[[1, 2, 3, 4, 5]]]]])

#access array 2d

In [ ]:
arr7

array([[[10, 20, 30],
        [20, 30, 60]],

       [[10, 20, 50],
        [ 1,  5,  8]]])

In [ ]:
arr7[0][1]

array([20, 30, 60])

In [ ]:
arr = np.array([[10,20,30,40,50,60],[70,80,90,100,110,120]])

In [ ]:
arr[0]

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr[1]

array([ 70,  80,  90, 100, 110, 120])

In [ ]:
arr[-1]

array([ 70,  80,  90, 100, 110, 120])

In [ ]:
arr[0,5] # like this or

60

In [ ]:
arr[0][5]# both are same

60

In [ ]:
# accessing second index
arr[1][-3]

100

In [ ]:
arr [1,-3]

100

#arithmatic operation based on index

In [ ]:
print(arr)

[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


In [ ]:
addition = arr[0,2] +arr[1,-1]

In [ ]:
addition # 30+120 returns 150

150

#access 3d array
* (1,2,3)

In [ ]:
_3d= np.array([[[10, 20, 30], [20, 30, 60]],[[10,20,50],[1,5,8]]])


In [ ]:
print(_3d)

[[[10 20 30]
  [20 30 60]]

 [[10 20 50]
  [ 1  5  8]]]


In [ ]:
_3d[0][1][2] #60

60

In [ ]:
_3d[1,0,-2] #20

20

In [ ]:
import numpy as np

new_array = [[[1,2,3,4,5],[2,5,4,81,15],[10,20,30,60,50]],[[10,20,30,40,50],[30,60,50,60,50],[20,50,60,40,30]]]
arr = np.array(new_array)

In [ ]:
arr.ndim

3

In [ ]:
arr[0][1][2]

4

In [ ]:
arr[0,1,2:]

array([ 4, 81, 15])

#slicing in 2d arrray

In [ ]:
arr1 = np.array([[10,20,30,40,50],[60,70,80,90,100]]) # want to print 70,80,90
print(arr1[1,1:4])

[70 80 90]


In [ ]:
arr1 = np.array([[10,20,30,40,50],[60,70,80,90,100]]) # want to print 10,20,30
print(arr1[0,:3]) # is equal to 0,0:3

[10 20 30]


#DATA TYPES IN NUMPY


* i - integer
* b - bool
* u - unsigned interger
* f - float
* c - complex
* m - timedelta
* M -datetime
* o -Object
* S -String
* V fixed chunk of memory
* U - unicode




## checking data type

In [ ]:
arr1 = np.array([[10,20,30,40,50],[60,70,80,90,100]]) # want to print 70,80,90
type(arr1)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr2 =np.array(['Hello','Kaise','Ho'])
arr2.dtype

dtype('<U5')

## creating array with defined data type

In [ ]:
arr3 = np.array([1,2,3,4,5] , dtype ='S')
print(arr3.dtype )
print("__________")
arr3

|S1
__________


array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

##creating an array with data type 4 bytes interger

* int 32 is 4 bytes

In [ ]:
arr4 = np.array ([1,2,3,4,5],dtype ='i4')
print(arr4)
arr4.dtype

[1 2 3 4 5]


dtype('int32')

#numpy array shape 2d array

In [ ]:
arr5 = np.array([[10,20,30,40,50],[25,35,45,65,55]])
print(arr5.shape) #2,4 means 2 nested arr and each arr has 5 data

(2, 5)


In [ ]:
arr5 = np.array([[10,20,40,50],[255,45,65,55]])
print(arr5.shape) #2,4

(2, 4)


In [ ]:
arr5 = np.array([[10,20,40,50],[255,45,65,55],[1,2,3,6]])
print(arr5.shape) #3,4

(3, 4)


In [ ]:
arr5 = np.array([[[10,20,40,50],[255,45,65,55],[1,2,3,6]]])
print(arr5.shape) #1,3,4
# it telling we have 1 3rd and 3 nested arr and 4 data

(1, 3, 4)


#Joining Numpy array

In [ ]:
arrA = np.array([1,2,3])
arrB = np.array([4,5,6])

result = np.concatenate((arrA , arrB))
result

array([1, 2, 3, 4, 5, 6])

In [ ]:
arrA = np.array([[1,2,3],[5,6,9,]])
arrB = np.array([[4,5,6],[10,20,30]])

result = np.concatenate((arrA , arrB), axis =0)
result

array([[ 1,  2,  3],
       [ 5,  6,  9],
       [ 4,  5,  6],
       [10, 20, 30]])

In [ ]:
arrA = np.array([[1,2,3],[5,6,9,]])
arrB = np.array([[4,5,6],[10,20,30]])

result = np.concatenate((arrA , arrB), axis =1)
result

array([[ 1,  2,  3,  4,  5,  6],
       [ 5,  6,  9, 10, 20, 30]])

#Spliting arrays

In [ ]:
arr = np.array([10,20,30,40,50])
splitting_arr = np.array_split(arr ,2) # here im saying make this inro 2 paRTS
splitting_arr

[array([10, 20, 30]), array([40, 50])]

In [ ]:

arr = np.array([10,20,30,40,50,60])
splitting_arr = np.array_split(arr ,3) # here im saying make this inro 3 paRTS
splitting_arr

[array([10, 20]), array([30, 40]), array([50, 60])]

#ravel and flatten

* it convert multi d array into single d arr

##both do the same thing

1. flatten():
Returns a copy of the array collapsed into one dimension.
Always returns a copy, so it might consume more memory.
Guarantees that changes made to the flattened array won't affect the original array.
2.  ravel():
Returns a flattened one-dimensional array, but it may return a view of the original array instead of a copy if possible.
If the returned array is a view, modifying it will modify the original array.
Generally, ravel() is more memory-efficient than flatten() because it doesn't create a copy if it's not necessary. ---

In [ ]:
data = np.array([[[1,0,2,3,5],[1,2,3,4,5],[5,4,3,2,1],[9,8,7,6,5]]])
print(data.dtype)
print('Dimension of :',data.ndim)
convert = data.ravel() #it converted into one
print("After convert :",convert)

int64
Dimension of : 3
After convert : [1 0 2 3 5 1 2 3 4 5 5 4 3 2 1 9 8 7 6 5]


In [ ]:
|

In [ ]:
data = np.array([[[1,0,2,3,5],[1,2,3,4,5],[5,4,3,2,1],[9,8,7,6,5]]])
print(data.dtype)
print('Dimension of :',data.ndim)
convert = data.flatten() #it converted into one
print("After convert :",convert)

int64
Dimension of : 3
After convert : [1 0 2 3 5 1 2 3 4 5 5 4 3 2 1 9 8 7 6 5]


array([[[1, 0, 2, 3, 5],
        [1, 2, 3, 4, 5],
        [5, 4, 3, 2, 1],
        [9, 8, 7, 6, 5]]])

#Unique()

##remove duplication

In [ ]:
arr = np.array([1,2,3,5,4,6,8,9,7,4,5,1,1,10,2,0,1,2,0,1,20,1,2,0,1,2,5,4,8,7,9,5,4,2,1,4,62,4,2,4,81,5,1,0,10,50,0,50,51])

print(arr)

distinct_value = np.unique(arr)
print("_____________")
print("The unique values are :",distinct_value)

[ 1  2  3  5  4  6  8  9  7  4  5  1  1 10  2  0  1  2  0  1 20  1  2  0
  1  2  5  4  8  7  9  5  4  2  1  4 62  4  2  4 81  5  1  0 10 50  0 50
 51]
_____________
The unique values are : [ 0  1  2  3  4  5  6  7  8  9 10 20 50 51 62 81]


In [ ]:
arr = np.array([1,2,3,5,4,6,8,9,7,4,5,1,1,10,2,0,1,2,0,1,20,1,2,0,1,2,5,4,8,7,9,5,4,2,1,4,62,4,2,4,81,5,1,0,10,50,0,50,51])

print(arr)

distinct_value = np.unique(arr, return_index=True)
print("_____________")
print("The unique values are :",distinct_value)

[ 1  2  3  5  4  6  8  9  7  4  5  1  1 10  2  0  1  2  0  1 20  1  2  0
  1  2  5  4  8  7  9  5  4  2  1  4 62  4  2  4 81  5  1  0 10 50  0 50
 51]
_____________
The unique values are : (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 20, 50, 51, 62, 81]), array([15,  0,  1,  2,  4,  3,  5,  8,  6,  7, 13, 20, 45, 48, 36, 40]))


In [ ]:
new_arr = np.array([10,20,30,40,50,10,25,36,30,40])
print("The array before Unique:",new_arr)
print("-------------------------------")
convert = np.unique(new_arr)
print("after new clearning :",convert)

The array before Unique: [10 20 30 40 50 10 25 36 30 40]
-------------------------------
after new clearning : [10 20 25 30 36 40 50]


In [ ]:
new_arr = np.array([10,20,30,40,50,10,25,36,30,40])
print("The array before Unique:",new_arr)
print("-------------------------------")
convert = np.unique(new_arr, return_index = True)
print("after new clearning :",convert,)

The array before Unique: [10 20 30 40 50 10 25 36 30 40]
-------------------------------
after new clearning : (array([10, 20, 25, 30, 36, 40, 50]), array([0, 1, 6, 2, 7, 3, 4]))


In [ ]:
new_arr = np.array([10,20,30,40,50,10,25,36,30,40])
print("The array before Unique:",new_arr)
print("-------------------------------")
convert = np.unique(new_arr, return_counts=True)
print("after new clearning :",convert,)

The array before Unique: [10 20 30 40 50 10 25 36 30 40]
-------------------------------
after new clearning : (array([10, 20, 25, 30, 36, 40, 50]), array([2, 1, 1, 2, 1, 2, 1]))


In [ ]:
new_arr

array([10, 20, 30, 40, 50, 10, 25, 36, 30, 40])

#delete

In [ ]:
np.delete(new_arr,1) # remove 20

array([10, 30, 40, 50, 10, 25, 36, 30, 40])

In [ ]:
x = np.array([[10,20,30,40,50],[60,50,10,20,30]])
print(x)
c =np.delete(x,1, axis =1) #column remove from each index 1 index values
c

[[10 20 30 40 50]
 [60 50 10 20 30]]


array([[10, 30, 40, 50],
       [60, 10, 20, 30]])

In [ ]:
x = np.array([[10,20,30,40,50],[60,50,10,20,30]])
print(x)
c =np.delete(x,1, axis =0) # remove row
c

[[10 20 30 40 50]
 [60 50 10 20 30]]


array([[10, 20, 30, 40, 50]])